// ============================================================
// MarketingKart.ai — Meta Ads Mock Data
// ============================================================

export const MOCK_AD_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 2999,
    duration: '7 Days',
    color: ['#3F51B5', '#5C6BC0'],
    estimatedReach: '10,000 – 25,000',
    estimatedLeads: '50 – 120',
    kpi: '50–120 Leads',
    features: ['1 Ad Creative', 'Basic Targeting', 'Email Support', 'Performance Report'],
  },
  {
    id: 'growth',
    name: 'Growth',
    price: 5999,
    duration: '15 Days',
    color: ['#7B1FA2', '#AB47BC'],
    estimatedReach: '40,000 – 80,000',
    estimatedLeads: '200 – 450',
    kpi: '200–450 Leads',
    features: ['3 Ad Creatives', 'Advanced Targeting', 'Priority Support', 'Weekly Report', 'A/B Testing'],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 9999,
    duration: '30 Days',
    color: ['#1565C0', '#1E88E5'],
    estimatedReach: '1,00,000 – 2,50,000',
    estimatedLeads: '500 – 1200',
    kpi: '500–1200 Leads',
    features: ['5 Ad Creatives', 'Premium Targeting', '24/7 Support', 'Daily Reports', 'A/B Testing', 'Remarketing'],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 19999,
    duration: '30 Days',
    color: ['#BF360C', '#E64A19'],
    estimatedReach: '3,00,000 – 7,00,000',
    estimatedLeads: '1500 – 4000',
    kpi: '1500–4000 Leads',
    features: ['Unlimited Creatives', 'Custom Targeting', 'Dedicated Manager', 'Real-time Dashboard', 'Full Funnel Strategy'],
  },
];

export const MOCK_INTERESTS = [
  {id: 'real_estate', label: 'Real Estate'},
  {id: 'home_decor', label: 'Home Decor'},
  {id: 'fitness', label: 'Fitness & Wellness'},
  {id: 'fashion', label: 'Fashion'},
  {id: 'food', label: 'Food & Dining'},
  {id: 'travel', label: 'Travel'},
  {id: 'education', label: 'Education'},
  {id: 'technology', label: 'Technology'},
  {id: 'beauty', label: 'Beauty & Skincare'},
  {id: 'automobile', label: 'Automobile'},
  {id: 'finance', label: 'Finance & Investment'},
  {id: 'healthcare', label: 'Healthcare'},
  {id: 'sports', label: 'Sports'},
  {id: 'gaming', label: 'Gaming'},
  {id: 'parenting', label: 'Parenting'},
  {id: 'pets', label: 'Pets'},
  {id: 'music', label: 'Music'},
  {id: 'photography', label: 'Photography'},
  {id: 'cooking', label: 'Cooking'},
  {id: 'yoga', label: 'Yoga & Meditation'},
  {id: 'entrepreneurship', label: 'Entrepreneurship'},
  {id: 'ecommerce', label: 'E-Commerce'},
];

export const MOCK_LOCATIONS = [
  {id: 'mumbai', label: 'Mumbai', state: 'Maharashtra'},
  {id: 'delhi', label: 'Delhi', state: 'Delhi'},
  {id: 'bangalore', label: 'Bengaluru', state: 'Karnataka'},
  {id: 'hyderabad', label: 'Hyderabad', state: 'Telangana'},
  {id: 'chennai', label: 'Chennai', state: 'Tamil Nadu'},
  {id: 'kolkata', label: 'Kolkata', state: 'West Bengal'},
  {id: 'pune', label: 'Pune', state: 'Maharashtra'},
  {id: 'ahmedabad', label: 'Ahmedabad', state: 'Gujarat'},
  {id: 'jaipur', label: 'Jaipur', state: 'Rajasthan'},
  {id: 'surat', label: 'Surat', state: 'Gujarat'},
  {id: 'lucknow', label: 'Lucknow', state: 'Uttar Pradesh'},
  {id: 'kanpur', label: 'Kanpur', state: 'Uttar Pradesh'},
  {id: 'nagpur', label: 'Nagpur', state: 'Maharashtra'},
  {id: 'indore', label: 'Indore', state: 'Madhya Pradesh'},
  {id: 'bhopal', label: 'Bhopal', state: 'Madhya Pradesh'},
  {id: 'visakhapatnam', label: 'Visakhapatnam', state: 'Andhra Pradesh'},
  {id: 'patna', label: 'Patna', state: 'Bihar'},
  {id: 'vadodara', label: 'Vadodara', state: 'Gujarat'},
  {id: 'gurgaon', label: 'Gurugram', state: 'Haryana'},
  {id: 'noida', label: 'Noida', state: 'Uttar Pradesh'},
  {id: 'coimbatore', label: 'Coimbatore', state: 'Tamil Nadu'},
  {id: 'kochi', label: 'Kochi', state: 'Kerala'},
  {id: 'chandigarh', label: 'Chandigarh', state: 'Punjab'},
  {id: 'goa', label: 'Goa', state: 'Goa'},
  {id: 'mysore', label: 'Mysuru', state: 'Karnataka'},
];

export const MOCK_NICHES = [
  {id: 'real_estate', label: 'Real Estate', icon: 'home', color: ['#1565C0', '#1E88E5']},
  {id: 'hotel', label: 'Hotel & Travel', icon: 'bed', color: ['#00695C', '#00897B']},
  {id: 'fashion', label: 'Fashion', icon: 'shirt', color: ['#AD1457', '#E91E63']},
  {id: 'food', label: 'Food & Dining', icon: 'restaurant', color: ['#E65100', '#FF5722']},
  {id: 'fitness', label: 'Fitness', icon: 'barbell', color: ['#2E7D32', '#43A047']},
  {id: 'education', label: 'Education', icon: 'school', color: ['#4527A0', '#7B1FA2']},
  {id: 'healthcare', label: 'Healthcare', icon: 'medical', color: ['#00838F', '#00ACC1']},
  {id: 'automobile', label: 'Automobile', icon: 'car', color: ['#37474F', '#546E7A']},
  {id: 'beauty', label: 'Beauty', icon: 'color-palette', color: ['#C2185B', '#E91E63']},
  {id: 'finance', label: 'Finance', icon: 'trending-up', color: ['#1B5E20', '#388E3C']},
  {id: 'ecommerce', label: 'E-Commerce', icon: 'cart', color: ['#E65100', '#F57C00']},
  {id: 'technology', label: 'Technology', icon: 'hardware-chip', color: ['#0D47A1', '#1976D2']},
];
