// ============================================================
// MarketingKart.ai — WhatsApp Module Mock Data
// ============================================================

export const MOCK_CONVERSATIONS = [
  {
    id: '1',
    customerName: 'Priya Sharma',
    customerPhone: '+91 98765 43210',
    lastMessage: 'Thank you! I received the order.',
    lastMessageTime: '10:42 AM',
    unreadCount: 2,
    avatarColor: '#7C3AED',
    status: 'active',
  },
  {
    id: '2',
    customerName: 'Rahul Mehta',
    customerPhone: '+91 91234 56789',
    lastMessage: 'Can you send me the invoice?',
    lastMessageTime: '9:15 AM',
    unreadCount: 0,
    avatarColor: '#0EA5E9',
    status: 'active',
  },
  {
    id: '3',
    customerName: 'Anjali Verma',
    customerPhone: '+91 99887 76655',
    lastMessage: 'Is the product still available?',
    lastMessageTime: 'Yesterday',
    unreadCount: 5,
    avatarColor: '#F59E0B',
    status: 'active',
  },
  {
    id: '4',
    customerName: 'Sanjay Patel',
    customerPhone: '+91 93456 12345',
    lastMessage: 'Please share the catalog.',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
    avatarColor: '#10B981',
    status: 'active',
  },
  {
    id: '5',
    customerName: 'Deepika Singh',
    customerPhone: '+91 88123 45678',
    lastMessage: 'When will the offer end?',
    lastMessageTime: 'Mon',
    unreadCount: 1,
    avatarColor: '#EF4444',
    status: 'active',
  },
  {
    id: '6',
    customerName: 'Vikram Nair',
    customerPhone: '+91 70045 67890',
    lastMessage: 'Got it, thanks!',
    lastMessageTime: 'Mon',
    unreadCount: 0,
    avatarColor: '#EC4899',
    status: 'active',
  },
  {
    id: '7',
    customerName: 'Meera Joshi',
    customerPhone: '+91 85567 89012',
    lastMessage: 'I want to place a bulk order.',
    lastMessageTime: 'Sun',
    unreadCount: 3,
    avatarColor: '#6366F1',
    status: 'active',
  },
];

export const MOCK_MESSAGES = [
  {
    id: '1',
    type: 'inbound',
    text: 'Hi, I saw your ad for the summer sale. Do you have any discounts available?',
    time: '10:01 AM',
    status: 'read',
  },
  {
    id: '2',
    type: 'outbound',
    text: 'Hello! Yes, we have an exclusive 30% off on all products until Sunday. Would you like to browse our catalog?',
    time: '10:03 AM',
    status: 'read',
  },
  {
    id: '3',
    type: 'inbound',
    text: 'That sounds great! Please send the catalog.',
    time: '10:05 AM',
    status: 'read',
  },
  {
    id: '4',
    type: 'outbound',
    text: 'Sure! Here's our catalog link: https://marketingkart.ai/catalog. You can also call us at 1800-XXX-XXXX for personal assistance.',
    time: '10:07 AM',
    status: 'delivered',
  },
  {
    id: '5',
    type: 'inbound',
    text: 'Perfect, I'll check it out. Do you offer free delivery?',
    time: '10:30 AM',
    status: 'read',
  },
  {
    id: '6',
    type: 'outbound',
    text: 'Yes! Free delivery on orders above ₹999. 🎉',
    time: '10:32 AM',
    status: 'sent',
  },
  {
    id: '7',
    type: 'inbound',
    text: 'Thank you! I received the order.',
    time: '10:42 AM',
    status: 'read',
  },
];

export const MOCK_CONTACTS = [
  {
    id: '1',
    name: 'Priya Sharma',
    phone: '+91 98765 43210',
    email: 'priya.sharma@email.com',
    note: 'Interested in bulk orders for summer collection.',
    status: 'active',
    tags: ['VIP', 'Bulk'],
  },
  {
    id: '2',
    name: 'Rahul Mehta',
    phone: '+91 91234 56789',
    email: 'rahul.mehta@email.com',
    note: 'Requested invoice for March purchases.',
    status: 'active',
    tags: ['Regular'],
  },
  {
    id: '3',
    name: 'Anjali Verma',
    phone: '+91 99887 76655',
    email: 'anjali.verma@email.com',
    note: 'Follow up on product availability query.',
    status: 'active',
    tags: ['New'],
  },
  {
    id: '4',
    name: 'Sanjay Patel',
    phone: '+91 93456 12345',
    email: 'sanjay.patel@biz.com',
    note: 'Needs product catalog and pricing.',
    status: 'inactive',
    tags: ['Prospect'],
  },
  {
    id: '5',
    name: 'Deepika Singh',
    phone: '+91 88123 45678',
    email: 'deepika.singh@email.com',
    note: 'Asked about ongoing offers.',
    status: 'active',
    tags: ['Regular'],
  },
  {
    id: '6',
    name: 'Vikram Nair',
    phone: '+91 70045 67890',
    email: 'vikram.nair@co.in',
    note: 'Completed purchase successfully.',
    status: 'active',
    tags: ['VIP'],
  },
  {
    id: '7',
    name: 'Meera Joshi',
    phone: '+91 85567 89012',
    email: 'meera.joshi@email.com',
    note: 'Interested in bulk ordering for retail outlet.',
    status: 'active',
    tags: ['Bulk', 'Prospect'],
  },
  {
    id: '8',
    name: 'Arjun Kumar',
    phone: '+91 76543 21098',
    email: 'arjun.kumar@email.com',
    note: 'New lead from Facebook campaign.',
    status: 'active',
    tags: ['New'],
  },
];

export const MOCK_WALLET = {
  balance: 2450.0,
  currency: '₹',
  transactions: [
    {
      id: 't1',
      type: 'CREDIT',
      description: 'Wallet Recharge via Razorpay',
      date: '12 Jun 2025',
      amount: 2000.0,
    },
    {
      id: 't2',
      type: 'DEBIT',
      description: 'Basic Plan - June 2025',
      date: '10 Jun 2025',
      amount: 999.0,
    },
    {
      id: 't3',
      type: 'CREDIT',
      description: 'Wallet Recharge via Razorpay',
      date: '2 Jun 2025',
      amount: 1500.0,
    },
    {
      id: 't4',
      type: 'DEBIT',
      description: 'Campaign: Summer Sale Blast',
      date: '1 Jun 2025',
      amount: 51.0,
    },
    {
      id: 't5',
      type: 'DEBIT',
      description: 'Campaign: New Arrivals Alert',
      date: '28 May 2025',
      amount: 36.0,
    },
    {
      id: 't6',
      type: 'CREDIT',
      description: 'Refund: Failed Campaign',
      date: '25 May 2025',
      amount: 36.0,
    },
    {
      id: 't7',
      type: 'DEBIT',
      description: 'Basic Plan - May 2025',
      date: '1 May 2025',
      amount: 999.0,
    },
  ],
};

export const MOCK_PLANS = [
  {
    id: 'starter',
    name: 'Starter',
    price: 499,
    period: 'month',
    contacts: 500,
    campaigns: 10,
    templates: 5,
    isCurrent: false,
    isBestValue: false,
    gradientColors: ['#64748B', '#475569'],
    features: ['500 Contacts', '10 Campaigns/month', '5 Templates', 'Basic Analytics', 'Email Support'],
  },
  {
    id: 'basic',
    name: 'Basic',
    price: 999,
    period: 'month',
    contacts: 2000,
    campaigns: 30,
    templates: 15,
    isCurrent: true,
    isBestValue: false,
    gradientColors: ['#3F51B5', '#5C6BC0'],
    features: ['2,000 Contacts', '30 Campaigns/month', '15 Templates', 'Advanced Analytics', 'Priority Support'],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 2499,
    period: 'month',
    contacts: 10000,
    campaigns: 100,
    templates: 50,
    isCurrent: false,
    isBestValue: true,
    gradientColors: ['#F59E0B', '#D97706'],
    features: ['10,000 Contacts', '100 Campaigns/month', '50 Templates', 'Custom Reports', 'Dedicated Manager'],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 9999,
    period: 'month',
    contacts: -1,
    campaigns: -1,
    templates: -1,
    isCurrent: false,
    isBestValue: false,
    gradientColors: ['#7C3AED', '#5B21B6'],
    features: ['Unlimited Contacts', 'Unlimited Campaigns', 'Unlimited Templates', 'White-label Option', '24/7 Support'],
  },
];

export const MOCK_PROFILE = {
  businessName: 'TrendMart Retail',
  ownerName: 'Rohit Kapoor',
  phone: '+91 98100 12345',
  email: 'rohit@trendmart.com',
  waNumber: '+91 98100 12345',
  waStatus: 'active',
  plan: 'Basic',
  stats: {
    campaigns: 18,
    templates: 12,
    contacts: 1843,
  },
};

export const MOCK_TICKETS = [
  {
    id: 'TKT-001',
    subject: 'Unable to send campaign messages',
    category: 'TECHNICAL',
    priority: 'HIGH',
    status: 'OPEN',
    date: '12 Jun 2025',
    message:
      'My campaign is stuck in queued state for the past 3 hours. I have 500 contacts and none of them received the message.',
  },
  {
    id: 'TKT-002',
    subject: 'Wallet recharge not reflecting',
    category: 'TRANSACTION',
    priority: 'HIGH',
    status: 'RESOLVED',
    date: '8 Jun 2025',
    message:
      'I paid ₹2000 via Razorpay but it is not showing in my wallet balance. Payment ID: pay_OJFf2XZnFE2kE6',
  },
  {
    id: 'TKT-003',
    subject: 'Need help with template approval',
    category: 'GENERAL',
    priority: 'MEDIUM',
    status: 'OPEN',
    date: '5 Jun 2025',
    message:
      'My template has been in PENDING state for 5 days. Please help me get it approved faster.',
  },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: 'n1',
    title: 'Campaign Completed 🎉',
    message: 'Your campaign "Summer Sale Blast" was delivered to 487/500 contacts successfully.',
    time: '2025-06-13T08:30:00Z',
    type: 'success',
    read: false,
  },
  {
    id: 'n2',
    title: 'Low Wallet Balance ⚠️',
    message: 'Your wallet balance is below ₹500. Recharge now to keep your campaigns running.',
    time: '2025-06-12T14:15:00Z',
    type: 'warning',
    read: false,
  },
  {
    id: 'n3',
    title: 'Template Approved ✅',
    message: 'Your template "Festival Offer" has been approved by WhatsApp. You can now use it in campaigns.',
    time: '2025-06-11T09:00:00Z',
    type: 'success',
    read: true,
  },
  {
    id: 'n4',
    title: 'New Message Received 💬',
    message: 'Priya Sharma replied to your campaign message. Open inbox to respond.',
    time: '2025-06-10T17:45:00Z',
    type: 'info',
    read: true,
  },
  {
    id: 'n5',
    title: 'Ticket Resolved 🎫',
    message: 'Your support ticket TKT-002 "Wallet recharge not reflecting" has been resolved.',
    time: '2025-06-08T11:20:00Z',
    type: 'success',
    read: true,
  },
];
