// ============================================================
// MarketingKart.ai — Mock Data for WhatsApp Marketing Module
// ============================================================

export const MOCK_WA_ACCOUNT = {
  id: 'wa_acc_001',
  status: 'CONNECTED',
  phoneNumber: '+91 98765 43210',
  displayName: 'MarketingKart Business',
  businessName: 'MarketingKart Solutions Pvt Ltd',
  wabaId: 'WABA_123456789',
  phoneNumberId: 'PH_987654321',
  qualityRating: 'GREEN',
  messagingLimit: '10000',
  connectedAt: '2024-01-15T10:30:00Z',
};

export const MOCK_TEMPLATES = [
  {
    id: 'tpl_001',
    name: 'festival_offer_2024',
    displayName: 'Festival Offer 2024',
    category: 'MARKETING',
    language: 'en_US',
    status: 'APPROVED',
    headerType: 'TEXT',
    headerText: '🎉 Special Festival Offer!',
    body: 'Hi {{1}}, celebrate this festive season with our exclusive {{2}} discount on all products! Valid till {{3}}. Shop now and save big. Use code: FEST2024',
    footer: 'Reply STOP to unsubscribe',
    buttons: [
      { type: 'URL', text: 'Shop Now', url: 'https://marketingkart.ai/shop' },
      { type: 'QUICK_REPLY', text: 'Get Offer' },
    ],
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-12T11:00:00Z',
  },
  {
    id: 'tpl_002',
    name: 'order_confirmation',
    displayName: 'Order Confirmation',
    category: 'UTILITY',
    language: 'en_US',
    status: 'APPROVED',
    headerType: 'TEXT',
    headerText: 'Order Confirmed ✅',
    body: 'Dear {{1}}, your order #{{2}} has been confirmed. Expected delivery: {{3}}. Track your order on our app.',
    footer: 'MarketingKart Solutions',
    buttons: [
      { type: 'URL', text: 'Track Order', url: 'https://marketingkart.ai/track' },
    ],
    createdAt: '2024-01-05T14:00:00Z',
    updatedAt: '2024-01-05T14:00:00Z',
  },
  {
    id: 'tpl_003',
    name: 'product_launch_promo',
    displayName: 'Product Launch Promo',
    category: 'MARKETING',
    language: 'en_US',
    status: 'PENDING',
    headerType: 'IMAGE',
    headerText: '',
    body: 'Hello {{1}}! We are thrilled to introduce our brand new {{2}}. Be among the first to experience it. Limited early bird pricing available!',
    footer: 'Terms & conditions apply',
    buttons: [
      { type: 'QUICK_REPLY', text: 'Interested!' },
      { type: 'URL', text: 'Learn More', url: 'https://marketingkart.ai/new' },
    ],
    createdAt: '2024-01-18T16:00:00Z',
    updatedAt: '2024-01-19T10:00:00Z',
  },
  {
    id: 'tpl_004',
    name: 'payment_reminder',
    displayName: 'Payment Reminder',
    category: 'UTILITY',
    language: 'en_US',
    status: 'APPROVED',
    headerType: 'NONE',
    headerText: '',
    body: 'Hi {{1}}, this is a gentle reminder that your payment of ₹{{2}} is due on {{3}}. Please make the payment to avoid service interruption.',
    footer: 'MarketingKart Finance',
    buttons: [
      { type: 'URL', text: 'Pay Now', url: 'https://marketingkart.ai/pay' },
      { type: 'CALL', text: 'Call Support', phone: '+919876543210' },
    ],
    createdAt: '2024-01-08T08:00:00Z',
    updatedAt: '2024-01-08T08:00:00Z',
  },
  {
    id: 'tpl_005',
    name: 'welcome_new_user',
    displayName: 'Welcome New User',
    category: 'MARKETING',
    language: 'hi_IN',
    status: 'REJECTED',
    headerType: 'TEXT',
    headerText: 'स्वागत है! 🙏',
    body: 'नमस्ते {{1}}! MarketingKart में आपका स्वागत है। हमारी सेवाओं का लाभ उठाएं और अपने व्यवसाय को नई ऊंचाइयों पर ले जाएं।',
    footer: 'MarketingKart.ai',
    buttons: [
      { type: 'QUICK_REPLY', text: 'शुरू करें' },
    ],
    createdAt: '2024-01-02T12:00:00Z',
    updatedAt: '2024-01-14T09:00:00Z',
    rejectionReason: 'Template contains promotional content without opt-in confirmation.',
  },
  {
    id: 'tpl_006',
    name: 'appointment_reminder',
    displayName: 'Appointment Reminder',
    category: 'UTILITY',
    language: 'en_US',
    status: 'APPROVED',
    headerType: 'NONE',
    headerText: '',
    body: 'Dear {{1}}, your appointment is scheduled for {{2}} at {{3}}. Please confirm your attendance or reschedule if needed.',
    footer: 'Reply YES to confirm',
    buttons: [
      { type: 'QUICK_REPLY', text: 'Confirm ✅' },
      { type: 'QUICK_REPLY', text: 'Reschedule' },
    ],
    createdAt: '2024-01-11T15:00:00Z',
    updatedAt: '2024-01-11T15:00:00Z',
  },
];

const generateMessageRows = (count, statuses) => {
  const names = ['Rahul Sharma', 'Priya Patel', 'Amit Kumar', 'Sunita Joshi', 'Vikram Singh',
    'Neha Gupta', 'Rajesh Verma', 'Pooja Mehta', 'Suresh Iyer', 'Kavita Reddy',
    'Arjun Nair', 'Meera Shah', 'Deepak Mishra', 'Anita Tiwari', 'Rohit Agarwal',
    'Sonia Chauhan', 'Manoj Yadav', 'Ritu Pandey', 'Anil Saxena', 'Geeta Bose'];
  return Array.from({ length: count }, (_, i) => ({
    id: `msg_${i + 1}`,
    phone: `+91 ${(9000000000 + i * 111111).toString().replace(/(\d{5})(\d{5})/, '$1 $2')}`,
    name: names[i % names.length],
    status: statuses[i % statuses.length],
    timestamp: new Date(Date.now() - i * 120000).toISOString(),
  }));
};

export const MOCK_CAMPAIGNS = [
  {
    id: 'camp_001',
    name: 'Diwali Festival Blast',
    status: 'COMPLETED',
    templateId: 'tpl_001',
    templateName: 'Festival Offer 2024',
    createdAt: '2024-01-20T10:00:00Z',
    scheduledAt: '2024-01-20T11:00:00Z',
    completedAt: '2024-01-20T11:45:00Z',
    stats: {
      total: 850,
      sent: 850,
      delivered: 812,
      read: 634,
      failed: 38,
    },
    deliveryRate: 95.5,
    messages: generateMessageRows(50, ['DELIVERED', 'READ', 'SENT', 'FAILED', 'READ', 'DELIVERED']),
  },
  {
    id: 'camp_002',
    name: 'New Year Promo Campaign',
    status: 'RUNNING',
    templateId: 'tpl_001',
    templateName: 'Festival Offer 2024',
    createdAt: '2024-01-22T09:00:00Z',
    scheduledAt: '2024-01-22T09:30:00Z',
    completedAt: null,
    stats: {
      total: 1200,
      sent: 780,
      delivered: 741,
      read: 502,
      failed: 39,
    },
    deliveryRate: 95.0,
    messages: generateMessageRows(40, ['SENT', 'DELIVERED', 'READ', 'FAILED', 'DELIVERED']),
  },
  {
    id: 'camp_003',
    name: 'Product Launch - Q1 2024',
    status: 'QUEUED',
    templateId: 'tpl_002',
    templateName: 'Order Confirmation',
    createdAt: '2024-01-23T14:00:00Z',
    scheduledAt: '2024-01-24T10:00:00Z',
    completedAt: null,
    stats: {
      total: 500,
      sent: 0,
      delivered: 0,
      read: 0,
      failed: 0,
    },
    deliveryRate: 0,
    messages: [],
  },
  {
    id: 'camp_004',
    name: 'Payment Reminder Batch',
    status: 'PAUSED',
    templateId: 'tpl_004',
    templateName: 'Payment Reminder',
    createdAt: '2024-01-19T08:00:00Z',
    scheduledAt: '2024-01-19T09:00:00Z',
    completedAt: null,
    stats: {
      total: 320,
      sent: 180,
      delivered: 171,
      read: 98,
      failed: 9,
    },
    deliveryRate: 95.0,
    messages: generateMessageRows(20, ['DELIVERED', 'READ', 'SENT', 'FAILED']),
  },
  {
    id: 'camp_005',
    name: 'Welcome Series Draft',
    status: 'DRAFT',
    templateId: 'tpl_006',
    templateName: 'Appointment Reminder',
    createdAt: '2024-01-23T16:00:00Z',
    scheduledAt: null,
    completedAt: null,
    stats: {
      total: 0,
      sent: 0,
      delivered: 0,
      read: 0,
      failed: 0,
    },
    deliveryRate: 0,
    messages: [],
  },
  {
    id: 'camp_006',
    name: 'Flash Sale Alert',
    status: 'FAILED',
    templateId: 'tpl_003',
    templateName: 'Product Launch Promo',
    createdAt: '2024-01-21T12:00:00Z',
    scheduledAt: '2024-01-21T13:00:00Z',
    completedAt: '2024-01-21T13:05:00Z',
    stats: {
      total: 400,
      sent: 12,
      delivered: 8,
      read: 3,
      failed: 388,
    },
    deliveryRate: 2.0,
    messages: generateMessageRows(12, ['FAILED', 'DELIVERED', 'READ']),
  },
];

export const MOCK_CONTACTS = [
  { id: 'con_001', name: 'Rahul Sharma', phone: '+919876543210', email: 'rahul@example.com', note: 'Premium customer' },
  { id: 'con_002', name: 'Priya Patel', phone: '+919876543211', email: 'priya@example.com', note: 'Lead from website' },
  { id: 'con_003', name: 'Amit Kumar', phone: '+919876543212', email: 'amit@example.com', note: '' },
  { id: 'con_004', name: 'Sunita Joshi', phone: '+919876543213', email: 'sunita@example.com', note: 'VIP member' },
  { id: 'con_005', name: 'Vikram Singh', phone: '+919876543214', email: 'vikram@example.com', note: '' },
  { id: 'con_006', name: 'Neha Gupta', phone: '+919876543215', email: 'neha@example.com', note: 'Referred by Rahul' },
  { id: 'con_007', name: 'Rajesh Verma', phone: '+919876543216', email: 'rajesh@example.com', note: '' },
  { id: 'con_008', name: 'Pooja Mehta', phone: '+919876543217', email: 'pooja@example.com', note: 'Newsletter subscriber' },
];

export const MOCK_DASHBOARD_STATS = {
  totalContacts: 2847,
  messagesSent: 12450,
  deliveryRate: 94.8,
  activeCampaigns: 2,
  totalCampaigns: 18,
  totalTemplates: 6,
  approvedTemplates: 4,
  walletBalance: 2350.00,
};

export const LANGUAGES = [
  { code: 'en_US', label: 'English (US)' },
  { code: 'hi_IN', label: 'Hindi (India)' },
  { code: 'en_GB', label: 'English (UK)' },
  { code: 'mr_IN', label: 'Marathi (India)' },
  { code: 'gu_IN', label: 'Gujarati (India)' },
  { code: 'ta_IN', label: 'Tamil (India)' },
  { code: 'te_IN', label: 'Telugu (India)' },
  { code: 'kn_IN', label: 'Kannada (India)' },
  { code: 'bn_IN', label: 'Bengali (India)' },
  { code: 'pa_IN', label: 'Punjabi (India)' },
];

export const VARIABLE_FIELD_OPTIONS = ['Name', 'Phone', 'Email', 'Note', 'Custom'];

// ============================================================
// Meta Ads Module Mock Data
// ============================================================

export const MOCK_ADS = [
  {
    id: '1',
    campaignName: 'Summer Sale Lead Gen',
    adType: 'Lead Ads',
    status: 'ACTIVE',
    thumbnail: null,
    startDate: '2024-06-01',
    endDate: '2024-06-30',
    impressions: 45200,
    views: 38100,
    leads: 320,
    clicks: 1540,
    spent: 4800,
    totalBudget: 6000,
    reach: 38100,
    platforms: 'FB + IG',
    area: 'Mumbai, Delhi',
    ageData: [
      {range: '18-24', pct: 20},
      {range: '25-34', pct: 35},
      {range: '35-44', pct: 25},
      {range: '45-54', pct: 15},
      {range: '55+', pct: 5},
    ],
    genderData: {male: 58, female: 38, other: 4},
    engagement: {bookmarks: 120, linkClicks: 540, reactions: 890, shares: 65},
    fbBudget: 3000,
    igBudget: 3000,
  },
  {
    id: '2',
    campaignName: 'WhatsApp Leads Q3',
    adType: 'WhatsApp Ads',
    status: 'IN_REVIEW',
    thumbnail: null,
    startDate: '2024-07-01',
    endDate: '2024-07-31',
    impressions: 12300,
    views: 9800,
    leads: 85,
    clicks: 430,
    spent: 2100,
    totalBudget: 4000,
    reach: 9800,
    platforms: 'FB',
    area: 'Bangalore, Pune',
    ageData: [
      {range: '18-24', pct: 18},
      {range: '25-34', pct: 40},
      {range: '35-44', pct: 22},
      {range: '45-54', pct: 14},
      {range: '55+', pct: 6},
    ],
    genderData: {male: 45, female: 50, other: 5},
    engagement: {bookmarks: 44, linkClicks: 210, reactions: 380, shares: 29},
    fbBudget: 4000,
    igBudget: 0,
  },
  {
    id: '3',
    campaignName: 'Brand Awareness Drive',
    adType: 'Awareness',
    status: 'COMPLETED',
    thumbnail: null,
    startDate: '2024-05-01',
    endDate: '2024-05-31',
    impressions: 98700,
    views: 85400,
    leads: 0,
    clicks: 3200,
    spent: 9800,
    totalBudget: 10000,
    reach: 85400,
    platforms: 'FB + IG',
    area: 'Pan India',
    ageData: [
      {range: '18-24', pct: 22},
      {range: '25-34', pct: 30},
      {range: '35-44', pct: 28},
      {range: '45-54', pct: 14},
      {range: '55+', pct: 6},
    ],
    genderData: {male: 52, female: 44, other: 4},
    engagement: {bookmarks: 320, linkClicks: 1200, reactions: 2100, shares: 180},
    fbBudget: 6000,
    igBudget: 4000,
  },
  {
    id: '4',
    campaignName: 'Website Traffic Boost',
    adType: 'Traffic',
    status: 'PAUSED',
    thumbnail: null,
    startDate: '2024-06-15',
    endDate: '2024-07-15',
    impressions: 22100,
    views: 18700,
    leads: 0,
    clicks: 2780,
    spent: 3500,
    totalBudget: 5000,
    reach: 18700,
    platforms: 'IG',
    area: 'Chennai, Hyderabad',
    ageData: [
      {range: '18-24', pct: 30},
      {range: '25-34', pct: 38},
      {range: '35-44', pct: 18},
      {range: '45-54', pct: 10},
      {range: '55+', pct: 4},
    ],
    genderData: {male: 60, female: 36, other: 4},
    engagement: {bookmarks: 88, linkClicks: 980, reactions: 460, shares: 72},
    fbBudget: 0,
    igBudget: 5000,
  },
  {
    id: '5',
    campaignName: 'Festive Season Leads',
    adType: 'Lead Ads',
    status: 'PREPARING',
    thumbnail: null,
    startDate: '2024-10-01',
    endDate: '2024-10-31',
    impressions: 0,
    views: 0,
    leads: 0,
    clicks: 0,
    spent: 0,
    totalBudget: 8000,
    reach: 0,
    platforms: 'FB + IG',
    area: 'All Metros',
    ageData: [
      {range: '18-24', pct: 20},
      {range: '25-34', pct: 35},
      {range: '35-44', pct: 25},
      {range: '45-54', pct: 15},
      {range: '55+', pct: 5},
    ],
    genderData: {male: 50, female: 46, other: 4},
    engagement: {bookmarks: 0, linkClicks: 0, reactions: 0, shares: 0},
    fbBudget: 4000,
    igBudget: 4000,
  },
  {
    id: '6',
    campaignName: 'App Install Campaign',
    adType: 'Traffic',
    status: 'DELIVERY_ERROR',
    thumbnail: null,
    startDate: '2024-06-20',
    endDate: '2024-07-20',
    impressions: 5400,
    views: 4200,
    leads: 0,
    clicks: 180,
    spent: 900,
    totalBudget: 3000,
    reach: 4200,
    platforms: 'FB',
    area: 'Delhi NCR',
    ageData: [
      {range: '18-24', pct: 35},
      {range: '25-34', pct: 40},
      {range: '35-44', pct: 15},
      {range: '45-54', pct: 8},
      {range: '55+', pct: 2},
    ],
    genderData: {male: 70, female: 27, other: 3},
    engagement: {bookmarks: 12, linkClicks: 85, reactions: 110, shares: 8},
    fbBudget: 3000,
    igBudget: 0,
  },
];

export const MOCK_AD_PLANS = [
  {
    id: 'plan_starter',
    name: 'Starter',
    price: 2500,
    duration: 7,
    fbBudget: 1500,
    igBudget: 1000,
    description: 'Best for testing campaigns',
    color: '#7986CB',
    features: ['7 days duration', 'FB + IG placement', 'Basic analytics'],
  },
  {
    id: 'plan_growth',
    name: 'Growth',
    price: 5000,
    duration: 14,
    fbBudget: 3000,
    igBudget: 2000,
    description: 'Great for growing brands',
    color: '#3F51B5',
    features: ['14 days duration', 'FB + IG + Stories', 'Advanced analytics', 'A/B testing'],
    popular: true,
  },
  {
    id: 'plan_pro',
    name: 'Pro',
    price: 10000,
    duration: 30,
    fbBudget: 6000,
    igBudget: 4000,
    description: 'Maximum reach & conversions',
    color: '#1877F2',
    features: ['30 days duration', 'All placements', 'Premium analytics', 'Dedicated support', 'Custom audience'],
  },
];

export const MOCK_FB_PAGES = [
  {id: 'page_1', name: 'MarketingKart Business', category: 'Marketing Agency', followers: '12.4K', avatar: null},
  {id: 'page_2', name: 'My Brand Store', category: 'Shopping & Retail', followers: '5.8K', avatar: null},
  {id: 'page_3', name: 'Tech Startup India', category: 'Technology', followers: '3.2K', avatar: null},
];

export const AD_TYPE_FILTERS = [
  {label: 'All', value: 'All'},
  {label: 'Lead Ads', value: 'Lead Ads'},
  {label: 'WhatsApp Ads', value: 'WhatsApp Ads'},
  {label: 'Traffic', value: 'Traffic'},
  {label: 'Awareness', value: 'Awareness'},
  {label: 'Engagement', value: 'Engagement'},
  {label: 'App Installs', value: 'App Installs'},
];
